nelmio_cors:
    paths:
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:3000$']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
